- hosts: all
  tasks:
  - name: Kubernetes key
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    become: yes
  - name: Kubernetes repository
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
    become: yes
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
    become: yes
  - name: full-upgrade
    apt:
      upgrade: full
      autoclean: yes
      autoremove: yes
    become: yes
  - name: Install fixed Kubernetes packages
    apt:
      name: 
      - kubeadm=1.20.5-00
      - kubectl=1.20.5-00
      - kubelet=1.20.5-00
      state: fixed
    become: yes
  - name: Install dependency packages
    apt:
      name: 
      - net-tools
      - unattended-upgrades
      - docker.io
      - software-properties-common
      - python3
      - python3-apt
      - python3-distutils
      - python-is-python3
      state: latest
    become: yes
  - name: Kubernetes iptables conf
    ansible.builtin.copy:
      src: sysctl_k8s.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: 0644
    become: yes
  - name: Docker Daemon conf
    ansible.builtin.copy:
      src: docker_daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0644
    become: yes
  - name: Get /boot/firmware/cmdline.txt
    ansible.builtin.slurp:
      src:  /boot/firmware/cmdline.txt
    register: boot_cmdline
    become: yes
  - name: print content of files
    debug:
      var: boot_cmdline.content|b64decode
  - name: Fix Docker cgroups
    ansible.builtin.command: 
      cmd: "sed -i '$ s/$/ {{item}}/' /boot/firmware/cmdline.txt"
      warn: false
    become: yes
    when: item not in boot_cmdline.content|b64decode
    loop:
      - 'group_enable=cpuset'
      - 'cgroup_enable=memory'
      - 'cgroup_memory=1'
      - 'swapaccount=1'
  - name: Test for pip in PATH
    ansible.builtin.shell: 
      cmd: "export PATH=${PATH}:${HOME}/.local/bi' ~/.bashrc"
    register: test_pip_path
    failed_when: "test_pip_path.rc > 1"
    changed_when: false
  - name: add pip bin to bashrc
    ansible.builtin.lineinfile:
      dest: ~/.bashrc
      line: "export PATH=${PATH}:${HOME}/.local/bi"
    when: test_pip_path.rc != "0"
  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
    become: yes

