apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rockset-server
  template:
    metadata:
      labels:
        app: rockset-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: rockset
        image: meyerkev248/storage:rockset
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
